### ISSUE TITLE
1.19.3

### ISSUE THREAD

**Issue by ccar795** [IMB11/FogLooksGoodNow#11]
The 1.1.0 file on curseforge says it works with 1.19.3 but the launcher says this:
![Screenshot 2023-02-24 221535](https://user-images.githubusercontent.com/21349871/221339786-31647f06-bf86-4e03-a389-35601c3eba29.png)

**Comment by IMB11** [comment]
Whoops! Open the jar in 7zip and edit the fabric.mod.json to set it to 1.19.3, I'll release a hotfix very soon

**Comment by ccar795** [comment]
Thank you.

**Comment by IMB11** [comment]
https://modrinth.com/mod/woof/version/3.0.0-1.19.3
