### ISSUE TITLE
Crash When Re-Loading a SinglePlayer World

### ISSUE THREAD

**Issue by LimyChitou** [IMB11/FogLooksGoodNow#16]
Reproducible Crash when attempting to reload a world
-
[crash-2023-03-23_13.37.47-client.txt](https://github.com/mineblock11/FogLooksGoodNow/files/11049868/crash-2023-03-23_13.37.47-client.txt)
-
I'm unsure whether I should report this here or to the PortLib.

**Comment by IMB11** [comment]
*Sigh* Porting Lib is an absolute pain in the god damn arse.

I'll release a hotfix that doesn't use it later.
