### ISSUE TITLE
Latest version broken on 1.19.4 despite 1.19.4 marked as supported on CurseForge

### ISSUE THREAD

**Issue by EthanRStokes** [IMB11/FogLooksGoodNow#18]
![image](https://user-images.githubusercontent.com/39657565/227810025-bc04f92a-b826-478e-b4d7-52761f327661.png)
![image](https://user-images.githubusercontent.com/39657565/227810038-318f4b6b-fe11-4fda-a0f7-20132b67b90a.png)

**Comment by IMB11** [comment]
Ah this is a publishing issue! It should just be 1.19.3. Fixing

**Comment by ghost** [comment]
The one on Modrinth has the same issue. The Modrinth page says that 1.1.4 is for both 1.19.3 and 1.19.4 when it's only for 1.19.3

**Comment by IMB11** [comment]
I'll report an issue on the mc-publish repository, will fix modrinth rn
