### ISSUE TITLE
Crash on startup 1.19.3

### ISSUE THREAD

**Issue by Cobyt3** [IMB11/FogLooksGoodNow#19]
as stated in the title. Trying to start the game, but it instantly crashes with Exit Code 1. It says owolib in the fabric.mod.json so I added that as well. Also added this file: [FogLooksGoodNow-1.1.4-sources.jar](https://www.curseforge.com/minecraft/mc-mods/fog-looks-good-now-fabric/files/4460089)

[latest.log](https://github.com/mineblock11/FogLooksGoodNow/files/11102482/latest.log)

**Comment by Lart-Iste** [comment]
Hi, same situation same version (mod & game), my log : https://paste.ee/p/WI04O

**Comment by IMB11** [comment]
Use loader 0.14.14 or below.
