### ISSUE TITLE
Instant crashing on Latest 1.19.3 Fabric (and Fabric API)

### ISSUE THREAD

**Issue by Kxsumi** [IMB11/FogLooksGoodNow#21]
I have no other mods inside of the folder and it's still crashing.
![image](https://user-images.githubusercontent.com/96434998/231024750-64f670d4-69c2-43ac-8217-73c9b9d468b8.png)
![image](https://user-images.githubusercontent.com/96434998/231024775-bb993cbb-01f1-49a1-948d-7d84ac805cd5.png)

**Comment by Kxsumi** [comment]
Nevermind, looked at the closed threads.

**Comment by Kxsumi** [comment]
Actually re-opening this. Still happens on 0.14.14.
![image](https://user-images.githubusercontent.com/96434998/231025512-ba8a4e62-4f84-4e49-b2ef-152c38af1b1f.png)

**Comment by IMB11** [comment]
Please post your logs, a screenshot is useless.

**Comment by Kxsumi** [comment]
https://paste.gg/p/anonymous/f6f6c1178d5e41e9a0bb1cd1e1e65726

**Comment by IMB11** [comment]
Using #22 for tracking.
