### ISSUE TITLE
1.20.1 Configuration does not apply

### ISSUE THREAD

**Issue by Leva25se** [IMB11/FogLooksGoodNow#25]
The values from the configuration file are not applied to the fog when loading the mod. Values are only applied when changing values via the in-game configuration editor and only until the game restarts.

fog-looks-good-now.json5:
```
{
	"biomeFogs": [],
	"defaultFogStart": 0.0,
	"defaultFogDensity": 0.0,
	"useCaveFog": true,
	"caveFogDensity": 0.8,
	"caveFogColor": 3355443
}
```
[latest.log](https://github.com/birsy/Fog-Looks-Good-Now/files/12182121/latest.log)

**Comment by IMB11** [comment]
Unable to reproduce

**Comment by IMB11** [comment]
Might be fixed for you when I migrate to YACL?

**Comment by antoine-hnkx** [comment]
@mineblock11 I'm able to reproduce the issue.

### Steps:
1. Launch a new minecraft instance with the mods and create a new world
2. Fog Start is at `0.0` by default
3. Change Fog Start to `0.5`
4. Confirm the changes (Click `Done` Button) and the fog updates correctly
5. Close the game and relaunch it
6. Enter the same world and notice the fog looks too close to be `0.5` Fog Start (It actually looks like it loaded the default value of `0.0`)
7. Open the mod settings and notice the slider is still on `0.5`, this is also the case in the config file. But the in-game fog doesn't respect this setting after re-launching the game.

**Note:** You can exit the world and re-enter the world without closing the game, the fog will still work correctly. It's only after re-launching the game.

### Screenshots:
Fog Start of `0.0` - Default Settings
<img src="https://github.com/mineblock11/FogLooksGoodNow/assets/65335212/91234030-e17d-40ec-a7e1-6541b3c57b06" width="250">

Fog Start of `0.5`
<img src="https://github.com/mineblock11/FogLooksGoodNow/assets/65335212/e79a9d47-89d3-4232-84cd-10d69293dd15" width="250">

After re-logging (No changes)
<img src="https://github.com/mineblock11/FogLooksGoodNow/assets/65335212/809e126c-1d6a-4922-a9e4-dea22ed5546f" width="250">

After re-launching - Fog (Looks the same as a value of `0.0`)
<img src="https://github.com/mineblock11/FogLooksGoodNow/assets/65335212/c3de59fa-42c2-4cf4-a675-1f33f56ff055" width="250">

After re-launching - Setting (Value of `0.5` is correct but not reflected in-game)
<img src="https://github.com/mineblock11/FogLooksGoodNow/assets/65335212/5db0f6ca-7b7f-49fa-bf8d-78095cdf904c" width="250">

### Instance Information:
```
Minecraft 1.20.2
Fabric API 0.90.7+1.20.2
Mod Menu 8.0.0
Fog Looks Good Now 1.3.2+1.20.2
```
Tested with both Modrinth launcher and Prism launcher.

**Comment by IMB11** [comment]
I will fix this in the next update which will make the configuration screen much nicer and easier to understand.
