### ISSUE TITLE
Cave fog bugs out when in water

### ISSUE THREAD

**Issue by donkeyrat** [IMB11/FogLooksGoodNow#32]
The sky goes completely dark and the clouds unrender when submerged in water partially. It seems to consider being in water as being in a cave?

![2023-12-25_19 28 11](https://github.com/IMB11/FogLooksGoodNow/assets/41966410/bf28faa0-2434-4c71-a8a3-705f9abab7c9)

**Comment by IMB11** [comment]
Probs because of the heightmap, will fix in the next update.
