### ISSUE TITLE
Fog not respecting setting after launch

### ISSUE THREAD

**Issue by wingedseahorse** [IMB11/FogLooksGoodNow#35]
Fabric 1.20.2
You can see in the first screenshot after launching the game the fog is coming up short and harsh. Tweaking the settings in the mod menu refreshes fog rendering and then it displays correctly. Third screenshot is vanilla for comparison. 
![Mod On Immediately after launch](https://github.com/IMB11/FogLooksGoodNow/assets/7261317/3f456382-4716-4a7e-bfcd-1dae3e9f0318)
![Mod Refreshed by toggling settings](https://github.com/IMB11/FogLooksGoodNow/assets/7261317/31e30fed-6a15-4793-a176-40a7f7e39f54)
![Vanilla](https://github.com/IMB11/FogLooksGoodNow/assets/7261317/a41dcc6e-44c6-446b-8653-78500a0dfa67)

**Comment by IMB11** [comment]
What version of FLGN are you using?

**Comment by wingedseahorse** [comment]
oops 2.0.0- 2.1.1 is working much better :+1:
