### ISSUE TITLE
Crash starting game on 2.1.1 with fabric 0.15.6-1.20.4,fabric api 0.95.1, mru 0.4.0

### ISSUE THREAD

**Issue by SqueakyPScott** [IMB11/FogLooksGoodNow#36]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'fog-looks-good-now'!

**Comment by IMB11** [comment]
Please upload the full log.

**Comment by SqueakyPScott** [comment]
[crash-2024-01-29_03.44.57-client.txt](https://github.com/IMB11/FogLooksGoodNow/files/14081841/crash-2024-01-29_03.44.57-client.txt)

**Comment by IMB11** [comment]
Install YACL.
