### ISSUE TITLE
Crashing With NullPointerException Error

### ISSUE THREAD

**Issue by SnazzyJovialWyrm** [IMB11/FogLooksGoodNow#4]
I've been experiencing random crashes here and there on Fabric 1.19.2, with Minecraft returning a NullPointerException error. Someone from the Fabric Project Discord Server suggested it may have something to do with PortingLib, which is included with this version of FogLooksGoodNow. They suggested that there may have not been a nullcheck with a temporary mixin variable, and that I should make an issue report about it. I've included the crash log in question that was used to deduce the problem:
[crashlog.txt](https://github.com/mineblock11/FogLooksGoodNow/files/10523364/crashlog.txt)

**Comment by IMB11** [comment]
Please report this to the porting lib team.
